package com.tlu.mylib_backend.enums;

public enum Language {
    AA("Afar"),
    AB("Abkhazian"),
    AF("Afrikaans"),
    AK("Akan"),
    SQ("Albanian"),
    AM("Amharic"),
    AR("Arabic"),
    AN("Aragonese"),
    HY("Armenian"),
    AS("Assamese"),
    AV("Avaric"),
    AE("Avestan"),
    AY("Aymara"),
    AZ("Azerbaijani"),
    BA("Bashkir"),
    BM("Bambara"),
    EU("Basque"),
    BE("Belarusian"),
    BN("Bengali"),
    BH("Bihari"),
    BI("Bislama"),
    BS("Bosnian"),
    BR("Breton"),
    BG("Bulgarian"),
    MY("Burmese"),
    CA("Catalan"),
    CH("Chamorro"),
    CE("Chechen"),
    NY("Chichewa"),
    ZH("Chinese"),
    CV("Chuvash"),
    KW("Cornish"),
    CO("Corsican"),
    CR("Cree"),
    HR("Croatian"),
    CS("Czech"),
    DA("Danish"),
    DV("Divehi"),
    NL("Dutch"),
    DZ("Dzongkha"),
    EN("English"),
    EO("Esperanto"),
    ET("Estonian"),
    EE("Ewe"),
    FO("Faroese"),
    FJ("Fijian"),
    FI("Finnish"),
    FR("French"),
    FY("Western Frisian"),
    FF("Fulah"),
    GD("Gaelic / Scottish Gaelic"),
    GA("Irish"),
    GL("Galician"),
    KA("Georgian"),
    DE("German"),
    EL("Greek"),
    GN("Guarani"),
    GU("Gujarati"),
    HT("Haitian"),
    HA("Hausa"),
    HE("Hebrew"),
    HZ("Herero"),
    HI("Hindi"),
    HO("Hiri Motu"),
    HU("Hungarian"),
    IA("Interlingua"),
    ID("Indonesian"),
    IE("Interlingue"),
    GAELIC("Irish Gaelic"),
    IG("Igbo"),
    IK("Inupiaq"),
    IO("Ido"),
    IS("Icelandic"),
    IT("Italian"),
    IU("Inuktitut"),
    JA("Japanese"),
    JV("Javanese"),
    KL("Kalaallisut"),
    KN("Kannada"),
    KR("Kanuri"),
    KS("Kashmiri"),
    KK("Kazakh"),
    KM("Khmer"),
    KI("Kikuyu"),
    RW("Kinyarwanda"),
    KY("Kirghiz"),
    KV("Komi"),
    KG("Kongo"),
    KO("Korean"),
    KJ("Kuanyama"),
    KU("Kurdish"),
    LO("Lao"),
    LA("Latin"),
    LV("Latvian"),
    LI("Limburgan"),
    LN("Lingala"),
    LT("Lithuanian"),
    LU("Luba-Katanga"),
    LG("Ganda"),
    MK("Macedonian"),
    MH("Marshallese"),
    ML("Malayalam"),
    MI("Maori"),
    MR("Marathi"),
    MS("Malay"),
    MG("Malagasy"),
    MT("Maltese"),
    MN("Mongolian"),
    NA("Nauru"),
    NV("Navajo"),
    ND("North Ndebele"),
    NR("South Ndebele"),
    NG("Ndonga"),
    NE("Nepali"),
    NO("Norwegian"),
    NB("Norwegian Bokmål"),
    NN("Norwegian Nynorsk"),
    II("Sichuan Yi"),
    OC("Occitan"),
    OJ("Ojibwa"),
    CU("Church Slavic"),
    OM("Oromo"),
    OR("Oriya"),
    OS("Ossetian"),
    PA("Punjabi"),
    PI("Pali"),
    FA("Persian"),
    PL("Polish"),
    PS("Pashto"),
    PT("Portuguese"),
    QU("Quechua"),
    RM("Romansh"),
    RN("Rundi"),
    RO("Romanian"),
    RU("Russian"),
    SA("Sanskrit"),
    SC("Sardinian"),
    SD("Sindhi"),
    SE("Northern Sami"),
    SM("Samoan"),
    SG("Sango"),
    SR("Serbian"),
    SN("Shona"),
    SI("Sinhala"),
    SK("Slovak"),
    SL("Slovenian"),
    SO("Somali"),
    ST("Southern Sotho"),
    ES("Spanish"),
    SU("Sundanese"),
    SW("Swahili"),
    SS("Swati"),
    SV("Swedish"),
    TA("Tamil"),
    TE("Telugu"),
    TG("Tajik"),
    TH("Thai"),
    TI("Tigrinya"),
    BO("Tibetan"),
    TK("Turkmen"),
    TL("Tagalog"),
    TN("Tswana"),
    TO("Tonga"),
    TR("Turkish"),
    TS("Tsonga"),
    TT("Tatar"),
    TW("Twi"),
    TY("Tahitian"),
    UG("Uighur"),
    UK("Ukrainian"),
    UR("Urdu"),
    UZ("Uzbek"),
    VE("Venda"),
    VI("Vietnamese"),
    VO("Volapük"),
    WA("Walloon"),
    CY("Welsh"),
    WO("Wolof"),
    XH("Xhosa"),
    YI("Yiddish"),
    YO("Yoruba"),
    ZA("Zhuang"),
    ZU("Zulu");

    private final String fullName;

    Language(String fullName) {
        this.fullName = fullName;
    }

    public String getFullName() {
        return fullName;
    }
}

